using System.Reflection;

#if TRIDION_71
    [assembly: AssemblyTitle("SDL DXA Provider for SDL Tridion 2013 SP1")]
#else
    [assembly: AssemblyTitle("SDL DXA Provider for SDL Web 8 (CDaaS)")]
#endif

// NOTE: Common Assembly Info is generated by the build in CommonAssemblyInfo.cs
