using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("SDL DXA Framework Models")]

#if DEBUG
    [assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif

[assembly: AssemblyCompany("SDL Group")]
[assembly: AssemblyProduct("SDL Digital Experience Accelerator")]
[assembly: AssemblyCopyright("Copyright © 2014-2016 SDL Group")]

[assembly: ComVisible(false)]

// NOTE: Version Info is generated by the build in VersionInfo.cs
