[assembly: System.Reflection.AssemblyVersion("0.0.0.0")]  // Generated by build
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.0.0")]  // Generated by build
[assembly: System.Reflection.AssemblyFileVersion("0.0.0.0")]  // Generated by build
